FROM mcr.microsoft.com/devcontainers/typescript-node:latest

# Install packages
# RUN apt-get update && apt-get install -y PACKAGE_NAME \
# 	&& rm -rf /var/lib/apt/lists/*

# Node.js
RUN npm install -g npm@latest pnpm@latest
